<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SmokingCessation.Common</AssemblyName>
    <RootNamespace>SmokingCessation.Common</RootNamespace>
  </PropertyGroup>

</Project>
